export type Role='owner'|'mechanic'|'warehouse'|'admin';
export type Provider={id:string|number;name:string;category:string;address:string;lat:number;lng:number;distance:string;rating:string;reviews:number;services:string[];mode:string;available:boolean;initials:string;color:string;stock:string[];inventory?:{name:string;category:string;price:number;quantity:number;availability:string}[];description?:string;phone?:string;email?:string;website?:string;canSchedule?:boolean};
export const providers:Provider[]=[
{id:1,name:'Sunset Auto Care',category:'Repair shop',address:'1250 9th Avenue, San Francisco',lat:37.765,lng:-122.466,distance:'1.2',rating:'4.9',reviews:128,services:['Oil change','Brakes','Diagnostics'],mode:'Mobile & shop',available:true,initials:'SA',color:'#ece6d9',stock:['Oil filter','Brake pads','Battery']},
{id:2,name:'Pacific Tire & Wheel',category:'Tire shop',address:'2320 Geary Boulevard, San Francisco',lat:37.782,lng:-122.443,distance:'1.8',rating:'4.8',reviews:96,services:['Tire repair','Tire rotation','Wheel alignment'],mode:'Shop visit',available:true,initials:'PT',color:'#e2e9f2',stock:['All-season tire','Tire repair kit']},
{id:3,name:'Bay City Roadside',category:'Towing',address:'675 Townsend Street, San Francisco',lat:37.77,lng:-122.405,distance:'2.4',rating:'4.9',reviews:214,services:['Towing','Jump start','Tire repair'],mode:'Mobile service',available:true,initials:'BC',color:'#f3e3d7',stock:['Battery','Tire repair kit']},
{id:4,name:'Golden Gate Motors',category:'Service dealership',address:'1800 Van Ness Avenue, San Francisco',lat:37.791,lng:-122.423,distance:'2.8',rating:'4.7',reviews:182,services:['Oil change','Diagnostics','Brakes'],mode:'Shop visit',available:false,initials:'GG',color:'#e5e1ee',stock:['Oil filter','Brake pads']},
{id:5,name:'Mission Auto Supply',category:'Auto-parts store',address:'2500 Mission Street, San Francisco',lat:37.756,lng:-122.419,distance:'3.1',rating:'4.8',reviews:75,services:['Parts','Battery testing'],mode:'Shop visit',available:true,initials:'MA',color:'#e8ebd6',stock:['Oil filter','Battery','Brake pads']},
{id:6,name:'Richmond Motor Works',category:'Repair shop',address:'4200 California Street, San Francisco',lat:37.785,lng:-122.464,distance:'2.1',rating:'4.8',reviews:89,services:['Diagnostics','Brakes','Oil change'],mode:'Mobile & shop',available:true,initials:'RM',color:'#dfebe5',stock:['Oil filter','Battery']},
];
export const initialVehicles=[{id:1,name:'The daily driver',make:'Toyota',model:'RAV4',year:2021,mileage:42850,plate:'8WGM214',color:'SILVER',status:'Service coming up'},{id:2,name:'Weekend explorer',make:'Subaru',model:'Outback',year:2019,mileage:67200,plate:'7BAY982',color:'FOREST GREEN',status:'All caught up'}];
export const initialRequests=[{id:'WM-2048',provider:'Sunset Auto Care',issue:'Battery won’t hold a charge',vehicle:'2021 Toyota RAV4',status:'In progress',date:'Today, 10:24 AM',mode:'Mobile service',mechanic:'Alex Morgan',notes:'Battery tested. Installing your replacement now.'},{id:'WM-2031',provider:'Pacific Tire & Wheel',issue:'Tire rotation and pressure check',vehicle:'2019 Subaru Outback',status:'Completed',date:'Sep 10, 2026',mode:'Shop visit',mechanic:'Jamie Chen',notes:'All four tires rotated and balanced.'}];
export const products=[{id:1,name:'Full synthetic motor oil',brand:'WINGMAN ESSENTIALS',category:'Oil & fluids',price:32.99,unit:'5 qt · SAE 0W-20',icon:'oil',color:'#e6edd6'},{id:2,name:'Premium engine oil filter',brand:'EVERYDAY PERFORMANCE',category:'Filters',price:12.49,unit:'Spin-on · single pack',icon:'filter',color:'#e5e7df'},{id:3,name:'All-weather wiper blades',brand:'CLEAR ROAD',category:'Wipers',price:24.99,unit:'26″ + 16″ · pair',icon:'wiper',color:'#dfe8ef'},{id:4,name:'12V AGM car battery',brand:'RELIABLE START',category:'Batteries',price:189.99,unit:'Group 35 · 650 CCA',icon:'battery',color:'#e9e3d9'},{id:5,name:'Ceramic brake pads',brand:'QUIET STOP',category:'Brakes',price:48.5,unit:'Front axle · set of 4',icon:'brake',color:'#e9e0de'},{id:6,name:'Cabin air filter',brand:'FRESH MILES',category:'Filters',price:18.99,unit:'Activated carbon · single pack',icon:'filter',color:'#e5e5ec'}];
export const initialCheckins=[{date:'Sep 1, 2026',mileage:42850,note:'A little slow to start on cold mornings.'},{date:'Aug 1, 2026',mileage:42040,note:'Everything feels good. Took a trip to Monterey.'},{date:'Jul 1, 2026',mileage:41220,note:'Slight vibration when braking. Booked an inspection.'}];
export const initialServices=[{id:1,date:'Jul 12, 2026',mileage:41600,provider:'Sunset Auto Care',items:['Oil change','Tire rotation','Brake inspection'],cost:149,invoice:'Service-invoice-july.pdf'},{id:2,date:'Apr 4, 2026',mileage:38200,provider:'Golden Gate Motors',items:['Scheduled maintenance','Cabin air filter'],cost:215,invoice:'Spring-maintenance.pdf'}];
export const initialAppointments=[{id:1,day:'22',month:'SEP',date:'Tuesday, September 22',time:'9:30 AM',service:'Oil change & inspection',provider:'Golden Gate Motors',vehicle:'2021 Toyota RAV4',status:'Confirmed'},{id:2,day:'28',month:'SEP',date:'Monday, September 28',time:'11:00 AM',service:'Wheel alignment',provider:'Pacific Tire & Wheel',vehicle:'2019 Subaru Outback',status:'Scheduled'}];
export const initialInventory=products.map((p,i)=>({...p,quantity:[24,4,18,3,12,8][i],sku:`WM-${1040+i}`,threshold:5}));
export const initialOrders=[{id:'PO-1084',buyer:'Sunset Auto Care',items:'Oil filters × 12, motor oil × 6',total:347.82,status:'Packed',date:'Today, 9:15 AM'},{id:'PO-1083',buyer:'Richmond Motor Works',items:'AGM batteries × 3',total:569.97,status:'Placed',date:'Today, 8:40 AM'},{id:'PO-1081',buyer:'Pacific Tire & Wheel',items:'Ceramic brake pads × 8',total:388,status:'Delivered',date:'Yesterday, 2:30 PM'}];
