import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, FileText, LoaderCircle, Plus, ReceiptText, X } from "lucide-react";
import { createRecordedInvoice, getRecordedInvoices, listRequests, updateRecordedInvoiceStatus } from "../api/endpoints";
import { useAuth } from "../context/AuthContext";
import { formatCurrencyUSD } from "../lib/formatters";

const blankItem = () => ({ description: "", quantity: 1, unit_price: "" });

export default function Billing() {
  const { user } = useAuth();
  const mechanic = user?.role === "mechanic";
  const [invoices, setInvoices] = useState([]);
  const [requests, setRequests] = useState([]);
  const [selected, setSelected] = useState(null);
  const [showCreate, setShowCreate] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const load = async () => {
    setLoading(true); setError("");
    try {
      const [invoiceRes, requestRes] = await Promise.all([getRecordedInvoices(), mechanic ? listRequests() : Promise.resolve({ data: [] })]);
      setInvoices(invoiceRes.data); setRequests(requestRes.data.filter((item) => item.mechanic_id));
    } catch (err) { setError(err.response?.data?.detail || "We could not load billing records."); }
    finally { setLoading(false); }
  };
  useEffect(() => { load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const paid = useMemo(() => invoices.filter((item) => item.status === "paid").reduce((sum, item) => sum + Number(item.total || 0), 0), [invoices]);
  return <main className="wingman-billing-page"><div className="wingman-billing-wrap"><header className="wingman-billing-hero"><div><p>Billing records</p><h1>{mechanic ? "Clear records for completed work." : "Your service records and receipts."}</h1><span>Wingman records invoices and payment status. It does not process payments.</span></div>{mechanic ? <button onClick={() => setShowCreate(true)}><Plus size={17} /> Create invoice</button> : null}</header><section className="wingman-billing-stats"><Stat label={mechanic ? "Recorded paid" : "Paid total"} value={formatCurrencyUSD(paid)} /><Stat label="Invoices" value={String(invoices.length)} /><Stat label="Open" value={String(invoices.filter((item) => item.status === "issued").length)} /></section>{error ? <p className="wingman-billing-error">{error}</p> : null}{loading ? <div className="wingman-billing-loading"><LoaderCircle className="animate-spin" /> Loading records…</div> : invoices.length ? <section className="wingman-invoice-grid">{invoices.map((invoice) => <button key={invoice.id} onClick={() => setSelected(invoice)} className="wingman-invoice-card"><div><span>{invoice.reference}</span><i className={`invoice-status ${invoice.status}`}>{invoice.status}</i></div><h2>{invoice.provider_name}</h2><p>{new Date(invoice.created_at).toLocaleDateString(undefined, { month: "long", day: "numeric", year: "numeric" })}</p><strong>{formatCurrencyUSD(invoice.total)}</strong></button>)}</section> : <section className="wingman-billing-empty"><ReceiptText size={27} /><h2>No invoices yet</h2><p>{mechanic ? "Create an invoice after completing work for an owner." : "Invoices from completed work will appear here."}</p></section>}{selected ? <InvoiceDetail invoice={selected} mechanic={mechanic} onClose={() => setSelected(null)} onUpdate={async (status) => { await updateRecordedInvoiceStatus(selected.id, { status }); setSelected((item) => ({ ...item, status })); await load(); }} /> : null}{showCreate ? <InvoiceCreate requests={requests} onClose={() => setShowCreate(false)} onCreated={() => { setShowCreate(false); load(); }} /> : null}</div></main>;
}

function Stat({ label, value }) { return <article><span>{label}</span><strong>{value}</strong></article>; }
function InvoiceDetail({ invoice, mechanic, onClose, onUpdate }) { return <div className="wingman-invoice-modal"><section><button className="wingman-modal-close" onClick={onClose}><X size={18} /></button><span className="wingman-modal-eyebrow">{invoice.reference}</span><h2>{invoice.provider_name}</h2><p className="wingman-muted">{new Date(invoice.created_at).toLocaleString()}</p><div className="wingman-invoice-lines">{invoice.items.map((item) => <div key={item.id}><span>{item.description} <small>× {item.quantity}</small></span><b>{formatCurrencyUSD(item.line_total)}</b></div>)}<div><span>Subtotal</span><b>{formatCurrencyUSD(invoice.subtotal)}</b></div><div><span>Taxes and fees</span><b>{formatCurrencyUSD(invoice.taxes_and_fees)}</b></div><div className="invoice-total"><strong>Total</strong><strong>{formatCurrencyUSD(invoice.total)}</strong></div></div>{invoice.provider_note ? <p className="wingman-invoice-note">{invoice.provider_note}</p> : null}{mechanic && invoice.status === "issued" ? <button className="wingman-mark-paid" onClick={() => onUpdate("paid")}><CheckCircle2 size={17} /> Record as paid</button> : <p className="wingman-invoice-state">Status: <b>{invoice.status}</b></p>}</section></div>; }
function InvoiceCreate({ requests, onClose, onCreated }) { const [requestId, setRequestId] = useState(requests[0]?.id || ""); const [items, setItems] = useState([blankItem()]); const [taxes, setTaxes] = useState(""); const [note, setNote] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const request = requests.find((item) => item.id === requestId); const updateItem = (index, key, value) => setItems((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item)); const submit = async (event) => { event.preventDefault(); if (!request) { setError("Select a completed or assigned job first."); return; } setSaving(true); setError(""); try { await createRecordedInvoice({ owner_id: request.owner_id, provider_name: "Wingman service provider", request_id: request.id, taxes_and_fees: Number(taxes || 0), provider_note: note || null, items: items.map((item) => ({ description: item.description, quantity: Number(item.quantity), unit_price: Number(item.unit_price) })) }); onCreated(); } catch (err) { setError(err.response?.data?.detail || "We could not create this invoice."); } finally { setSaving(false); } }; return <div className="wingman-invoice-modal"><section><button className="wingman-modal-close" onClick={onClose}><X size={18} /></button><span className="wingman-modal-eyebrow">New billing record</span><h2>Create an invoice</h2><form onSubmit={submit} className="wingman-invoice-form"><label>Completed work<select value={requestId} onChange={(e) => setRequestId(e.target.value)}>{requests.map((item) => <option value={item.id} key={item.id}>{item.owner_name || "Owner"} · {item.problem_desc}</option>)}</select></label>{items.map((item, index) => <div className="wingman-line-editor" key={index}><input placeholder="Work or part" required value={item.description} onChange={(e) => updateItem(index, "description", e.target.value)} /><input aria-label="Quantity" type="number" min="1" required value={item.quantity} onChange={(e) => updateItem(index, "quantity", e.target.value)} /><input aria-label="Unit price" type="number" min="0" step="0.01" required placeholder="$0.00" value={item.unit_price} onChange={(e) => updateItem(index, "unit_price", e.target.value)} /></div>)}<button className="wingman-add-line" type="button" onClick={() => setItems((current) => [...current, blankItem()])}>+ Add line item</button><label>Taxes and fees<input type="number" min="0" step="0.01" value={taxes} onChange={(e) => setTaxes(e.target.value)} /></label><label>Provider note<textarea value={note} onChange={(e) => setNote(e.target.value)} /></label>{error ? <p className="wingman-billing-error">{error}</p> : null}<button disabled={saving} className="wingman-create-invoice">{saving ? "Creating…" : "Create recorded invoice"}</button></form></section></div>; }
