import { useEffect, useMemo, useState } from "react";
import { Activity, ArrowUpRight, CalendarDays, CarFront, CheckCircle2, ClipboardList, HeartPulse, LoaderCircle, Map, MessageCircle, Package, ReceiptText, ShieldCheck, ShoppingBag, Store, UserRound, Wrench } from "lucide-react";
import { Link } from "react-router-dom";
import {
  getAlerts, getAnalytics, getMechanicDashboard, getMyMechanicProfile, getMyVehicles, getMyWarehouseProfile,
  getOwnerNotifications, getOwnerPartOrders, getProviderBookings, getRecordedInvoices, getWarehouseInbox,
  getWarehouseInventory, getWarehouseOrders, listAppointments, listRequests,
} from "../api/endpoints";
import { useAuth } from "../context/AuthContext";
import { formatCurrencyUSD } from "../lib/formatters";

const roleCopy = {
  owner: { eyebrow: "Your Wingman", title: "Everything about your vehicle, in one clear place.", description: "Find help, manage appointments, keep up with Vehicle Care, and keep every record close.", accent: "owner" },
  mechanic: { eyebrow: "Mechanic workspace", title: "The next job, with the context you need.", description: "Keep requests, appointments, inventory, billing, and customer conversations moving together.", accent: "mechanic" },
  warehouse: { eyebrow: "Warehouse workspace", title: "Fulfillment that stays in motion.", description: "See inventory, orders, delivery progress, and messages from one operating view.", accent: "warehouse" },
  admin: { eyebrow: "Network operations", title: "A clear view of the whole network.", description: "Review activity, providers, requests, alerts, and the health of Wingman at a glance.", accent: "admin" },
};

export default function WorkspaceHome() {
  const { user } = useAuth(); const role = user?.role || "owner"; const copy = roleCopy[role] || roleCopy.owner;
  const [data, setData] = useState({}); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { let live = true; async function load() { setLoading(true); setError(""); try { let result = {}; if (role === "owner") { const [requests, vehicles, bookings, orders, notes, invoices] = await Promise.all([listRequests(), getMyVehicles(), getProviderBookings(), getOwnerPartOrders(), getOwnerNotifications(), getRecordedInvoices()]); result = { requests: requests.data, vehicles: vehicles.data, bookings: bookings.data, orders: orders.data, notes: notes.data, invoices: invoices.data }; } else if (role === "mechanic") { const profile = await getMyMechanicProfile(); const [summary, requests, appointments, invoices] = await Promise.all([getMechanicDashboard(profile.data.mechanic_id, { range: "week" }), listRequests(), listAppointments(), getRecordedInvoices()]); result = { profile: profile.data, summary: summary.data, requests: requests.data, appointments: appointments.data, invoices: invoices.data }; } else if (role === "warehouse") { const [profile, inventory, orders, inbox] = await Promise.all([getMyWarehouseProfile(), getWarehouseInventory(), getWarehouseOrders(), getWarehouseInbox()]); result = { profile: profile.data, inventory: inventory.data, orders: orders.data, inbox: inbox.data }; } else { const [analytics, alerts] = await Promise.all([getAnalytics({ range: "week" }), getAlerts()]); result = { analytics: analytics.data, alerts: alerts.data }; } if (live) setData(result); } catch (err) { if (live) setError(err.response?.data?.detail || "Some workspace data could not be loaded."); } finally { if (live) setLoading(false); } } load(); return () => { live = false; }; }, [role]);
  const actions = useMemo(() => actionsFor(role), [role]);
  return <main className={`wingman-home wingman-home-${copy.accent}`}><div className="wingman-home-wrap"><header className="wingman-home-hero"><div><p>{copy.eyebrow}</p><h1>{copy.title}</h1><span>{copy.description}</span></div><div className="wingman-home-person"><UserRound size={18} /><div><b>{user?.name}</b><small>{role}</small></div></div></header>{error ? <p className="wingman-home-error">{error}</p> : null}{loading ? <div className="wingman-home-loading"><LoaderCircle className="animate-spin" /> Loading your workspace…</div> : <><section className="wingman-home-stats">{statsFor(role, data).map((item) => <article key={item.label}><item.icon size={18} /><span>{item.label}</span><strong>{item.value}</strong><small>{item.note}</small></article>)}</section><section className="wingman-home-layout"><div className="wingman-home-primary"><section className="wingman-home-section"><div className="wingman-section-heading"><div><p>In motion</p><h2>{role === "owner" ? "Your next steps" : role === "admin" ? "Network activity" : "Work needing attention"}</h2></div><Activity size={20} /></div><ActivityList role={role} data={data} /></section><section className="wingman-action-grid">{actions.map((action) => <Link key={action.to} to={action.to}><action.icon size={19} /><div><b>{action.label}</b><span>{action.detail}</span></div><ArrowUpRight size={17} /></Link>)}</section></div><aside className="wingman-home-aside"><section className="wingman-home-section"><div className="wingman-section-heading"><div><p>At a glance</p><h2>{role === "owner" ? "Keep close" : role === "mechanic" ? "Today’s work" : role === "warehouse" ? "Fulfillment" : "Network health"}</h2></div></div><Snapshot role={role} data={data} /></section><Link className="wingman-home-profile" to="/profile"><UserRound size={18} /><span><b>Profile and preferences</b><small>Keep your workspace up to date</small></span><ArrowUpRight size={16} /></Link></aside></section></>}</div></main>;
}

function actionsFor(role) { const all = { owner: [[Map, "Find service", "Map, providers, appointments and parts", "/explore"], [HeartPulse, "Vehicle Care", "Mileage, reminders, notes and records", "/vehicles"], [ReceiptText, "Billing", "Your invoices and receipts", "/billing"], [ClipboardList, "Requests", "Track roadside help", "/my-requests"]], mechanic: [[ClipboardList, "Jobs", "Requests, progress and messages", "/jobs"], [Package, "Inventory", "Parts ready for the next job", "/inventory"], [ReceiptText, "Billing", "Record completed work", "/billing"], [CalendarDays, "Appointments", "Scheduled customer visits", "/jobs"]], warehouse: [[Store, "Fulfillment", "Orders in progress", "/warehouse"], [Package, "Inventory", "Stock and low-stock alerts", "/warehouse"], [MessageCircle, "Messages", "Coordinate each order", "/warehouse"], [ShoppingBag, "Orders", "Delivery and pickup status", "/warehouse"]], admin: [[ShieldCheck, "Network controls", "Accounts and approvals", "/admin"], [Activity, "Analytics", "Demand and completion trends", "/admin"], [Wrench, "Service requests", "Keep requests moving", "/admin"], [MessageCircle, "Alerts", "Resolve network issues", "/admin"]] }; return all[role].map(([icon, label, detail, to]) => ({ icon, label, detail, to })); }
function statsFor(role, data) { if (role === "owner") return [{ icon: CarFront, label: "Vehicles", value: data.vehicles?.length || 0, note: "in your garage" }, { icon: CalendarDays, label: "Appointments", value: data.bookings?.length || 0, note: "scheduled or requested" }, { icon: HeartPulse, label: "Reminders", value: data.notes?.filter((item) => !item.completed_at).length || 0, note: "need attention" }, { icon: ReceiptText, label: "Invoices", value: data.invoices?.length || 0, note: "kept together" }]; if (role === "mechanic") return [{ icon: Wrench, label: "Active jobs", value: data.summary?.active_jobs || 0, note: "currently moving" }, { icon: CheckCircle2, label: "Completed", value: data.summary?.completed_jobs || 0, note: "this period" }, { icon: CalendarDays, label: "Appointments", value: data.appointments?.length || 0, note: "on the calendar" }, { icon: ReceiptText, label: "Recorded", value: formatCurrencyUSD(data.invoices?.filter((i) => i.status === "paid").reduce((sum, i) => sum + Number(i.total || 0), 0) || 0), note: "paid invoices" }]; if (role === "warehouse") return [{ icon: ShoppingBag, label: "Open orders", value: data.orders?.filter((item) => !["delivered", "cancelled"].includes(item.status)).length || 0, note: "in fulfillment" }, { icon: Package, label: "Stocked products", value: data.inventory?.length || 0, note: "in inventory" }, { icon: Activity, label: "Low stock", value: data.inventory?.filter((item) => Number(item.quantity) <= Number(item.min_threshold)).length || 0, note: "need restocking" }, { icon: MessageCircle, label: "Messages", value: data.inbox?.length || 0, note: "active conversations" }]; const summary = data.analytics?.summary || {}; return [{ icon: UserRound, label: "Accounts", value: summary.total_users || 0, note: "across all roles" }, { icon: Wrench, label: "Requests", value: summary.total_requests || 0, note: "this period" }, { icon: CheckCircle2, label: "Completed", value: summary.completed_requests || 0, note: "work completed" }, { icon: Activity, label: "Alerts", value: data.alerts?.length || 0, note: "need review" }]; }
function ActivityList({ role, data }) { let items = []; if (role === "owner") items = [...(data.bookings || []).slice(0, 2).map((item) => [item.provider_name, item.service_type]), ...(data.orders || []).slice(0, 2).map((item) => [item.product_name || item.order_ref, item.status])]; else if (role === "mechanic") items = (data.requests || []).slice(0, 4).map((item) => [item.owner_name || "Vehicle owner", `${item.problem_desc} · ${item.status.replaceAll("_", " ")}`]); else if (role === "warehouse") items = (data.orders || []).slice(0, 4).map((item) => [item.order_ref || "Order", `${item.mechanic_name || "Mechanic"} · ${item.status}`]); else items = (data.alerts || []).slice(0, 4).map((item) => [item.alert_type || "Network alert", item.message]); if (!items.length) return <p className="wingman-list-empty">Nothing needs attention right now.</p>; return <div className="wingman-activity-list">{items.map(([title, detail], index) => <article key={`${title}-${index}`}><i>{index + 1}</i><div><b>{title}</b><span>{detail}</span></div></article>)}</div>; }
function Snapshot({ role, data }) { if (role === "owner") return <div className="wingman-snapshot"><b>{data.vehicles?.[0] ? `${data.vehicles[0].year} ${data.vehicles[0].make} ${data.vehicles[0].model}` : "Your garage is ready"}</b><p>{data.notes?.length ? `${data.notes.length} Vehicle Care notification${data.notes.length === 1 ? "" : "s"} are available.` : "Add a vehicle to begin tracking care and service history."}</p><Link to="/vehicles">Open Vehicle Care <ArrowUpRight size={15} /></Link></div>; if (role === "mechanic") return <div className="wingman-snapshot"><b>{data.profile?.is_available ? "Accepting new work" : "Currently unavailable"}</b><p>{data.profile?.specialization || "Keep your profile and service availability current."}</p><Link to="/profile">Update availability <ArrowUpRight size={15} /></Link></div>; if (role === "warehouse") return <div className="wingman-snapshot"><b>{data.profile?.name || "Warehouse profile"}</b><p>{data.inventory?.filter((item) => Number(item.quantity) <= Number(item.min_threshold)).length || 0} products are at or below their stock threshold.</p><Link to="/warehouse">Review inventory <ArrowUpRight size={15} /></Link></div>; return <div className="wingman-snapshot"><b>Wingman network</b><p>{data.analytics?.mechanics_online || 0} mechanics are currently online. Review alerts and approvals to keep coverage healthy.</p><Link to="/admin">Open controls <ArrowUpRight size={15} /></Link></div>; }
