"use client";
import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,Check,MapPin,Minus,PackageCheck,Plus,Search,ShoppingBag,Truck} from 'lucide-react';
import {createOwnerPartOrder,getOwnerMarketplaceParts,getOwnerPartOrders} from '../../api/endpoints';
import {Badge,Empty,Modal,PageTitle} from './prototype-shared';

type Product={id:string;name:string;brand?:string;category:string;price:number;stock_count:number;description?:string;retailer_name:string;retailer_city:string;synthetic_phone?:string};
type Order={id:string;order_ref:string;quantity:number;unit_price:number;total_price:number;status:string;delivery_name:string;delivery_address:string;delivery_phone:string;delivery_notes?:string;created_at:string;product_name:string;retailer_name:string};
const statusLabels:Record<string,string>={confirmed:'Confirmed',processing:'Processing',shipped:'On the way',delivered:'Delivered',cancelled:'Cancelled'};

export default function PartsMarketplace({notify}:{notify:(message:string)=>void}){
 const [products,setProducts]=useState<Product[]>([]),[orders,setOrders]=useState<Order[]>([]),[cart,setCart]=useState<Record<string,number>>({}),[query,setQuery]=useState(''),[category,setCategory]=useState('all'),[modal,setModal]=useState(''),[loading,setLoading]=useState(true),[submitting,setSubmitting]=useState(false);
 const live=typeof window!=='undefined'&&Boolean(localStorage.getItem('token'));
 async function refresh(){if(!live){setLoading(false);return}try{const [partRes,orderRes]=await Promise.all([getOwnerMarketplaceParts(),getOwnerPartOrders()]);setProducts(partRes.data||[]);setOrders(orderRes.data||[])}catch(e:any){notify(e?.response?.data?.detail||'Parts marketplace could not be loaded.')}finally{setLoading(false)}}
 useEffect(()=>{refresh()},[]);
 const categories=useMemo(()=>['all',...Array.from(new Set(products.map(p=>p.category)))],[products]);
 const shown=products.filter(p=>(category==='all'||p.category===category)&&`${p.name} ${p.brand||''} ${p.retailer_name} ${p.description||''}`.toLowerCase().includes(query.trim().toLowerCase()));
 const selected=products.filter(p=>cart[p.id]);
 const count=selected.reduce((n,p)=>n+cart[p.id],0),total=selected.reduce((n,p)=>n+p.price*cart[p.id],0);
 function quantity(id:string,delta:number){const product=products.find(p=>p.id===id);if(!product)return;setCart(current=>({...current,[id]:Math.max(0,Math.min(product.stock_count,(current[id]||0)+delta))}))}
 async function checkout(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!selected.length)return;const form=new FormData(event.currentTarget),delivery_name=String(form.get('name')||''),delivery_address=String(form.get('address')||''),delivery_phone=String(form.get('phone')||''),delivery_notes=String(form.get('notes')||'');setSubmitting(true);try{for(const product of selected){await createOwnerPartOrder({product_id:product.id,quantity:cart[product.id],delivery_name,delivery_address,delivery_phone,delivery_notes:delivery_notes||null})}setCart({});await refresh();setModal('orders');notify('Order confirmed. Delivery tracking is now available in your orders.')}catch(e:any){notify(e?.response?.data?.detail||'The order could not be placed. Please review the delivery details.')}finally{setSubmitting(false)}}
 return <div className="retail-marketplace">
  <PageTitle title="Parts shop" action={<button className="primary" onClick={()=>setModal('bag')}><ShoppingBag size={18}/> Your bag <span className="count-light">{count}</span></button>}/>
  <div className="retail-disclosure"><span>Wingman marketplace</span><p>Fixed-price maintenance products from the California demo directory. Orders and delivery details are saved to your account; payment is recorded outside Wingman.</p></div>
  <div className="retail-utility"><span><MapPin size={16}/> California delivery</span><button className="text-button" onClick={()=>setModal('orders')}>Your orders {orders.length>0&&`(${orders.length})`}<ArrowRight size={16}/></button></div>
  <label className="search-input retail-search"><Search size={18}/><input aria-label="Search parts" placeholder="Search products, brands, or retailers" value={query} onChange={e=>setQuery(e.target.value)}/></label>
  <div className="filter-row retail-categories">{categories.map(item=><button key={item} className={'chip '+(category===item?'selected':'')} aria-pressed={category===item} onClick={()=>setCategory(item)}>{item==='all'?'All parts':item}</button>)}</div>
  {loading?<div className="panel empty-state"><p>Loading available parts…</p></div>:shown.length?<div className="retail-product-list">{shown.map(product=><article className="retail-product" key={product.id}><div className="retail-product-copy"><span className="overline">{product.category}</span><h3>{product.name}</h3><p>{product.brand||product.retailer_name} · {product.retailer_city}</p>{product.description&&<p>{product.description}</p>}<span className="retail-stock"><Check size={14}/> {product.stock_count} in stock · Delivery</span></div><div className="retail-product-buy"><strong>${Number(product.price).toFixed(2)}</strong><small>{product.retailer_name}</small>{cart[product.id]?<div className="quantity"><button aria-label={`Decrease ${product.name}`} onClick={()=>quantity(product.id,-1)}><Minus size={14}/></button><span>{cart[product.id]}</span><button aria-label={`Increase ${product.name}`} onClick={()=>quantity(product.id,1)}><Plus size={14}/></button></div>:<button className="secondary" disabled={!product.stock_count} onClick={()=>quantity(product.id,1)}><Plus size={16}/> Add to bag</button>}</div></article>)}</div>:<Empty title="No matching parts" text="Try another product, brand, retailer, or category."/>}
  {modal==='bag'&&<Modal title="Delivery checkout" subtitle={count?`${count} item${count===1?'':'s'} · $${total.toFixed(2)}`:'Your bag is empty'} wide onClose={()=>setModal('')}>{!count?<Empty title="Your bag is empty" text="Add a fixed-price product to begin an order."/>:<><div className="cart-items">{selected.map(p=><div className="cart-item" key={p.id}><div><h3>{p.name}</h3><p>{p.retailer_name} · ${Number(p.price).toFixed(2)} each</p></div><div className="quantity"><button onClick={()=>quantity(p.id,-1)}><Minus size={14}/></button><span>{cart[p.id]}</span><button onClick={()=>quantity(p.id,1)}><Plus size={14}/></button></div><strong>${(p.price*cart[p.id]).toFixed(2)}</strong></div>)}</div><div className="cart-total between"><strong>Recorded total</strong><strong>${total.toFixed(2)}</strong></div><form className="form-grid" onSubmit={checkout}><div className="form-columns"><label>Delivery name<input name="name" required minLength={2} autoComplete="name"/></label><label>Contact number<input name="phone" required minLength={7} type="tel" autoComplete="tel"/></label></div><label>Delivery address<textarea name="address" required minLength={8} autoComplete="street-address"/></label><label>Delivery notes (optional)<textarea name="notes" placeholder="Access instructions or a safe delivery note"/></label><p className="muted">No online payment is collected. This creates a recorded fixed-price demo order and reduces the displayed stock.</p><button className="primary full" disabled={submitting}><Truck size={17}/>{submitting?'Placing order…':'Place delivery order'}<ArrowRight size={17}/></button></form></>}</Modal>}
  {modal==='orders'&&<Modal title="Your parts orders" subtitle="Saved delivery orders and their latest status" wide onClose={()=>setModal('')}>{!orders.length?<Empty title="No orders yet" text="Add a maintenance product and enter delivery details to place your first order."/>:<div className="retail-order-list">{orders.map(order=><article className="retail-order" key={order.id}><div className="between"><h3>{order.order_ref}</h3><Badge tone={order.status==='delivered'?'green':'gray'}>{statusLabels[order.status]||order.status}</Badge></div><strong>{order.quantity} × {order.product_name}</strong><p>{order.retailer_name} · ${Number(order.total_price).toFixed(2)}</p><p><Truck size={15}/> {order.delivery_address}</p><p>{order.delivery_name} · {order.delivery_phone}</p>{order.delivery_notes&&<p>{order.delivery_notes}</p>}{order.status==='delivered'&&<p className="retail-stock"><PackageCheck size={17}/> Delivered</p>}</article>)}</div>}</Modal>}
 </div>
}
