"use client";
import {useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,MapPin,Search,ShoppingBag,Plus,Minus,Check,Store,PackageCheck} from 'lucide-react';
import {Modal,PageTitle,Empty,Badge} from './prototype-shared';
import {products} from '@/lib/demo-data';

const stores=[
{id:'oreilly',name:"O’Reilly Auto Parts",branch:'16th Street',address:'2300 16th Street, San Francisco, CA 94103',url:'https://locations.oreillyauto.com/en-us/ca/sanfrancisco/autoparts-3032.html',accent:'#91cbb0',label:'O’Reilly',highlights:[1,4,3],items:[1,2,3,4,5,6],note:'Oil, batteries & everyday maintenance'},
{id:'autozone',name:'AutoZone',branch:'Howard Street',address:'1375 Howard Street, San Francisco, CA 94103',url:'https://www.autozone.com/locations/ca/san-francisco/1375-howard-street',accent:'#e9b08d',label:'AutoZone',highlights:[5,3,1],items:[1,2,3,5,6],note:'Brakes, wipers & weekend essentials'},
{id:'napa',name:'NAPA Auto Parts',branch:'Evans Avenue',address:'1640 Evans Ave, San Francisco, CA',url:'https://www.napaonline.com/en/ca/san-francisco/store/26167?store=30976',accent:'#b2c5ec',label:'NAPA',highlights:[2,6,4],items:[1,2,4,5,6],note:'Filters, batteries & garage essentials'},
];
type Shop=typeof stores[number];
type Order={id:string;store:Shop;items:{name:string;quantity:number;price:number}[];total:number;status:number;contact:string};
const stages=['Placed','Preparing','Ready for pickup','Picked up'];
export default function PartsMarketplace({notify}:{notify:(message:string)=>void}){
 const [shop,setShop]=useState<Shop|null>(null),[bagShop,setBagShop]=useState<Shop|null>(null),[cart,setCart]=useState<Record<number,number>>({}),[pending,setPending]=useState<Shop|null>(null),[query,setQuery]=useState(''),[category,setCategory]=useState('All parts'),[storeQuery,setStoreQuery]=useState(''),[modal,setModal]=useState(''),[orders,setOrders]=useState<Order[]>([]);
 const count=Object.values(cart).reduce((a,b)=>a+b,0), total=products.reduce((a,p)=>a+p.price*(cart[p.id]||0),0);
 const catalog=products.filter(p=>shop?.items.includes(p.id));
 const results=catalog.filter(p=>(category==='All parts'||p.category===category)&&`${p.name} ${p.category} ${p.unit}`.toLowerCase().includes(query.toLowerCase().trim()));
 const filtered=query.trim()!==''||category!=='All parts';
 function enter(s:Shop){if(count&&bagShop?.id!==s.id){setPending(s);setModal('switch');return;}setShop(s);setQuery('');setCategory('All parts');}
 function add(id:number){if(!shop)return;setBagShop(shop);setCart({...cart,[id]:(cart[id]||0)+1});notify('Added to your pickup bag. Demo inventory.');}
 function productRow(p:typeof products[number],featured=false){return <article key={p.id} className={'retail-product '+(featured?'featured':'')}><div className="retail-product-copy"><span className="overline">{p.category}</span><h3>{p.name}</h3><p>{p.unit}</p><span className="retail-stock"><Check size={14}/> Demo stock · Pickup</span></div><div className="retail-product-buy"><strong>${p.price.toFixed(2)}</strong><small>Demo price</small><button className="secondary" onClick={()=>add(p.id)} aria-label={`Add ${p.name} to pickup bag`}><Plus size={16}/> Add{cart[p.id]?` · ${cart[p.id]} in bag`:''}</button></div></article>}
 return <div className="retail-marketplace">
 <PageTitle title="Parts shop" action={<button className="primary" onClick={()=>setModal('bag')}><ShoppingBag size={18}/> Your bag <span className="count-light">{count}</span></button>}/>
 <div className="retail-disclosure"><span>Demo inventory</span><p>Real store names and locations. Products, prices, stock and pickup activity are illustrative. Stores are not participating in Wingman.</p></div>
 <div className="retail-utility">{shop?<button className="text-button" onClick={()=>setShop(null)}><ArrowLeft size={16}/> All stores</button>:<span><MapPin size={16}/> San Francisco, California</span>}<button className="text-button" onClick={()=>setModal('orders')}>Pickup orders {orders.length>0&&`(${orders.length})`}<ArrowUpRight size={16}/></button></div>
 {!shop?<><label className="search-input retail-search"><Search size={18}/><input aria-label="Search stores" placeholder="Search by store name or street" value={storeQuery} onChange={e=>setStoreQuery(e.target.value)}/></label><div className="retail-section-heading"><h2>Choose your store</h2><span>Pickup only</span></div><div className="retail-stores">{stores.filter(s=>`${s.name} ${s.address}`.toLowerCase().includes(storeQuery.toLowerCase().trim())).map(s=><article className="retail-store panel" key={s.id} style={{'--store-accent':s.accent} as React.CSSProperties}><div className="retail-store-wordmark">{s.label}<span>Auto parts</span></div><div className="retail-store-body"><Badge tone="gray">Demo inventory</Badge><h3>{s.name}</h3><p className="retail-branch">{s.branch}</p><p className="retail-address"><MapPin size={16}/>{s.address}</p><p>{s.note}<br/><small>Illustrative catalog · {s.items.length} products</small></p><button className="primary full" onClick={()=>enter(s)}>Shop this store <ArrowRight size={17}/></button><a href={s.url} target="_blank" rel="noreferrer" className="retail-source">Official store listing <ArrowUpRight size={13}/></a></div></article>)}</div>{!stores.some(s=>`${s.name} ${s.address}`.toLowerCase().includes(storeQuery.toLowerCase().trim()))&&<Empty title="No stores found" text="Try AutoZone, NAPA, O’Reilly, or a San Francisco street name."/>}</>:<>
 <div className="retail-store-context"><div><MapPin size={20}/><div><strong>{shop.branch} · Pickup location</strong><p>{shop.address}</p></div></div><a href={shop.url} target="_blank" rel="noreferrer" className="text-button">Store listing <ArrowUpRight size={14}/></a></div>
 <label className="search-input retail-search"><Search size={20}/><input aria-label="Search parts in this store" placeholder={`Search ${shop.name} demo parts…`} value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="text-button" onClick={()=>setQuery('')}>Clear</button>}</label>
 <div className="filter-row retail-categories">{['All parts',...new Set(catalog.map(p=>p.category))].map(c=><button className={'chip '+(category===c?'selected':'')} aria-pressed={category===c} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div>
 {!filtered&&<section><div className="retail-section-heading"><div><h2>Store highlights</h2><p>A few everyday essentials to get you started.</p></div><span>Demo selection</span></div><div className="retail-highlights">{shop.highlights.map(id=>products.find(p=>p.id===id)!).map(p=>productRow(p,true))}</div></section>}
 <section><div className="retail-section-heading"><h2>{filtered?'Matching parts':'All parts'} <span>({results.length})</span></h2>{filtered&&<button className="text-button" onClick={()=>{setQuery('');setCategory('All parts')}}>Reset filters</button>}</div><div className="retail-product-list">{results.map(p=>productRow(p))}</div>{!results.length&&<Empty title="No matching parts in this demo" text="Try oil, filter, battery, wipers, or clear your filters."/>}</section>
 <p className="retail-fitment">Product specifications are illustrative. Vehicle compatibility has not been verified. Confirm fitment with the store before any real purchase.</p>
 </>}
 {modal==='switch'&&pending&&<Modal title="Start a bag at another store?" subtitle={`Your current bag contains ${count} item${count===1?'':'s'} from ${bagShop?.name}. Orders are limited to one store.`} onClose={()=>{setModal('');setPending(null)}}><p>Switching to {pending.name} will clear the current bag.</p><div className="button-row"><button className="secondary" onClick={()=>{setModal('');setPending(null)}}>Keep current bag</button><button className="primary" onClick={()=>{setCart({});setBagShop(null);setShop(pending);setPending(null);setQuery('');setCategory('All parts');setModal('')}}>Clear bag & switch</button></div></Modal>}
 {modal==='bag'&&<Modal title="Your pickup bag" subtitle={bagShop?`${bagShop.name} · ${bagShop.branch}`:'One store per order · Pickup only'} wide onClose={()=>setModal('')}>{!count?<Empty title="Your bag is empty" text="Choose a store and add a few essentials to try pickup checkout."/>:<><div className="retail-store-context"><MapPin size={20}/><div><strong>Pickup at {bagShop?.name}</strong><p>{bagShop?.address}</p></div></div><div className="cart-items">{products.filter(p=>cart[p.id]).map(p=><div className="cart-item" key={p.id}><div><h3>{p.name}</h3><p>${p.price.toFixed(2)} each · Demo price</p></div><div className="quantity"><button aria-label={`Decrease ${p.name} quantity`} onClick={()=>setCart({...cart,[p.id]:Math.max(0,cart[p.id]-1)})}><Minus size={14}/></button><span>{cart[p.id]}</span><button aria-label={`Increase ${p.name} quantity`} onClick={()=>setCart({...cart,[p.id]:cart[p.id]+1})}><Plus size={14}/></button></div><strong>${(p.price*cart[p.id]).toFixed(2)}</strong></div>)}</div><div className="cart-total between"><strong>Demo subtotal</strong><strong>${total.toFixed(2)}</strong></div><form className="form-grid" onSubmit={e=>{e.preventDefault();if(!bagShop)return;const contact=String(new FormData(e.currentTarget).get('contact'));setOrders([{id:`PU-${Date.now().toString().slice(-6)}`,store:bagShop,items:products.filter(p=>cart[p.id]).map(p=>({name:p.name,quantity:cart[p.id],price:p.price})),total,status:0,contact},...orders]);setCart({});setBagShop(null);setModal('orders');notify('Demo pickup order created. The store has not been contacted.')}}><div className="form-columns"><label>Pickup contact<input name="contact" required defaultValue="Jordan Ellis"/></label><label>Contact phone<input name="phone" type="tel" required defaultValue="415-555-0100"/></label></div><p className="muted">Use sample contact details. No payment is collected, stock reserved, or pickup arranged with the real store.</p><button className="primary full">Place demo pickup order <ArrowRight size={17}/></button></form></>}</Modal>}
 {modal==='orders'&&<Modal title="Your pickup orders" subtitle="Demonstration only. Do not travel to a store for these orders." wide onClose={()=>setModal('')}>{!orders.length?<Empty title="No pickup orders yet" text="Choose a store to try your first demo order."/>:orders.map(o=><article className="retail-order" key={o.id}><div className="between"><h3>{o.id}</h3><Badge>{stages[o.status]}</Badge></div><strong>{o.store.name} · {o.store.branch}</strong><p>{o.store.address}</p><p>Pickup contact: {o.contact}</p><ul>{o.items.map(i=><li key={i.name}>{i.quantity} × {i.name}</li>)}</ul><p>Demo subtotal · ${o.total.toFixed(2)}</p><div className="order-steps">{stages.map((stage,i)=><span key={stage} className={i===o.status?'active':''}>{stage}</span>)}</div>{o.status<3?<button className="text-button" onClick={()=>setOrders(orders.map(x=>x.id===o.id?{...x,status:x.status+1}:x))}>Preview next pickup stage <ArrowRight size={15}/></button>:<p className="retail-stock"><PackageCheck size={17}/> Demo pickup completed</p>}</article>)}</Modal>}
 </div>
}
