"use client";
import {X,ArrowUpRight,CarFront,Battery,Disc3,Droplets,Wind,Package,CheckCircle2} from 'lucide-react';import {useEffect,useRef} from 'react';
export function Modal({title,subtitle,children,onClose,wide=false}:{title:string;subtitle?:string;children:React.ReactNode;onClose:()=>void;wide?:boolean}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();const d=ref.current;return()=>d?.close()},[]);return <dialog ref={ref} className={'modal '+(wide?'wide':'')} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose()}}><header><div><h2>{title}</h2>{subtitle&&<p className="muted">{subtitle}</p>}</div><button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={21}/></button></header>{children}</dialog>}
export function PageTitle({eyebrow,title,description,action}:{eyebrow?:string;title?:string;description?:string;action?:React.ReactNode}){return <div className={"page-title"+(!eyebrow&&!title&&!description?" action-only":"")} >{(eyebrow||title||description)&&<div>{eyebrow&&<span className="overline">{eyebrow}</span>}{title&&<h1>{title}</h1>}{description&&<p>{description}</p>}</div>}{action}</div>}
export function Badge({children,tone='green'}:{children:React.ReactNode;tone?:string}){return <span className={'badge '+tone}>{children}</span>}
export function Empty({title,text}:{title:string;text:string}){return <div className="empty-state"><Package size={35}/><h3>{title}</h3><p>{text}</p></div>}
export function CarArt({dark=false}:{dark?:boolean}){return <svg className="car-art" viewBox="0 0 420 160" role="img" aria-label={dark?'Forest green crossover vehicle':'Silver crossover vehicle'}><ellipse cx="214" cy="140" rx="172" ry="9" fill="#20382e12"/><path d="M40 105 49 76 106 63 145 25Q220 15 284 28L329 65 373 77 386 116 374 128H47L32 119Z" fill={dark?'#496553':'#c7cfcc'} stroke={dark?'#38513f':'#a6b0a9'} strokeWidth="2"/><path d="m120 64 35-32 49-3v36Zm94-35 61 6 37 31-96-1Z" fill="#52665f"/><path d="M43 100h331M205 70v48M312 72l12 45" stroke={dark?'#76907d':'#a2aea6'} strokeWidth="2"/><rect x="175" y="77" width="18" height="3" rx="2" fill="#71857a"/><rect x="281" y="78" width="18" height="3" rx="2" fill="#71857a"/><path d="m49 80 33-5-8 12H46m293-9 31 8 5 9-30-4" fill="#f5f3db"/>{[104,322].map(x=><g key={x}><circle cx={x} cy="120" r="28" fill="#26362e"/><circle cx={x} cy="120" r="17" fill="#a7b1a8"/><circle cx={x} cy="120" r="10" fill="#697a70"/><circle cx={x} cy="120" r="4" fill="#dce1d9"/></g>)}</svg>}
export function ProductArt({type}:{type:string}){const Icon=type==='oil'?Droplets:type==='battery'?Battery:type==='brake'?Disc3:type==='wiper'?Wind:Package;return <div className={'product-object '+type}><Icon size={52} strokeWidth={1.25}/><span>{type==='oil'?'0W–20':type==='battery'?'12V / AGM':type==='filter'?'PREMIUM':'WINGMAN'}</span></div>}
export function Stat({label,value,change,icon}:{label:string;value:string;change:string;icon:React.ReactNode}){return <div className="stat-card"><div><span>{label}</span>{icon}</div><strong>{value}</strong><small>{change}</small></div>}
export function Toast({text,onClose}:{text:string;onClose:()=>void}){useEffect(()=>{const id=setTimeout(onClose,4500);return()=>clearTimeout(id)},[text,onClose]);return <div className="toast" role="status"><CheckCircle2 size={20}/>{text}<button onClick={onClose} aria-label="Dismiss notification"><X size={16}/></button></div>}
export function Field({label,children}:{label:string;children:React.ReactNode}){return <label>{label}{children}</label>}
