"use client";
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,MapPin,Search} from 'lucide-react';
import {createWarehouseOrderGroup,getWarehouseDetail,getWarehouseMarketplace} from '../../api/endpoints';
import {Empty,Modal} from './prototype-shared';

type Warehouse={id:string;name:string;address:string;available_parts:number;low_stock_parts:number};
type Part={id:string;part_name:string;part_number?:string;quantity:number;price:number;manufacturer?:string;lead_time_label?:string};
export default function WarehouseMarketplace({onOrder}:{onOrder:(warehouse:string,item:string,quantity:number,total:number,order?:any)=>void}){
 const [warehouses,setWarehouses]=useState<Warehouse[]>([]),[store,setStore]=useState<Warehouse|null>(null),[parts,setParts]=useState<Part[]>([]),[query,setQuery]=useState(''),[selected,setSelected]=useState<Part|null>(null),[loading,setLoading]=useState(true),[submitting,setSubmitting]=useState(false),[error,setError]=useState('');
 const live=typeof window!=='undefined'&&Boolean(localStorage.getItem('token'));
 useEffect(()=>{if(!live){setLoading(false);return}getWarehouseMarketplace({lat:37.7749,lng:-122.4194,radius_km:5000}).then(r=>setWarehouses(r.data||[])).catch(e=>setError(e?.response?.data?.detail||'Warehouses could not be loaded.')).finally(()=>setLoading(false))},[]);
 async function openStore(warehouse:Warehouse){setStore(warehouse);setLoading(true);setError('');try{const {data}=await getWarehouseDetail(warehouse.id);setParts(data.inventory||[])}catch(e:any){setError(e?.response?.data?.detail||'Warehouse inventory could not be loaded.')}finally{setLoading(false)}}
 const visibleStores=warehouses.filter(item=>`${item.name} ${item.address}`.toLowerCase().includes(query.toLowerCase()));
 const visibleParts=parts.filter(item=>`${item.part_name} ${item.part_number||''} ${item.manufacturer||''}`.toLowerCase().includes(query.toLowerCase()));
 async function order(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!store||!selected)return;const form=new FormData(event.currentTarget),quantity=Number(form.get('quantity')),note=String(form.get('note')||'');setSubmitting(true);try{const {data}=await createWarehouseOrderGroup({warehouse_id:store.id,items:[{warehouse_part_id:selected.id,quantity}],note:note||null});onOrder(store.name,selected.part_name,quantity,Number(selected.price)*quantity,data);setSelected(null)}catch(e:any){setError(e?.response?.data?.detail||'The parts order could not be placed.')}finally{setSubmitting(false)}}
 return <><p className="muted">Live Wingman warehouse inventory and recorded fixed-price orders.</p>{error&&<p className="form-error">{error}</p>}<label className="search-input retail-search"><Search size={18}/><input aria-label={store?'Search products':'Search warehouses'} placeholder={store?'Search products or SKUs':'Search warehouses or locations'} value={query} onChange={e=>setQuery(e.target.value)}/></label>{loading?<p className="muted">Loading marketplace…</p>:!store?<div className="retail-stores">{visibleStores.map(warehouse=><article className="panel section-panel" key={warehouse.id}><h2>{warehouse.name}</h2><p><MapPin size={15}/> {warehouse.address}</p><p className="muted">{warehouse.available_parts} products · {warehouse.low_stock_parts} low stock</p><button className="primary" onClick={()=>{setQuery('');openStore(warehouse)}}>Browse products <ArrowRight size={17}/></button></article>)}{!visibleStores.length&&<Empty title="No warehouses found" text="Try another warehouse or location."/ >}</div>:<><button className="text-button" onClick={()=>{setStore(null);setParts([]);setQuery('')}}><ArrowLeft size={17}/> All warehouses</button><div className="retail-section-heading"><h2>{store.name}</h2><span>{store.address}</span></div><div className="retail-product-list">{visibleParts.map(part=><article className="retail-product" key={part.id}><div><h3>{part.part_name}</h3><p>{part.manufacturer||part.part_number||'Automotive part'}</p><small>{part.quantity} units · {part.lead_time_label||'Available'}</small></div><div className="retail-product-buy"><strong>${Number(part.price).toFixed(2)}</strong><small>Per unit</small><button className="secondary" disabled={!part.quantity} onClick={()=>setSelected(part)}>Order</button></div></article>)}</div>{!visibleParts.length&&<Empty title="No matching products" text="Try another product or SKU."/>}</>}{selected&&store&&<Modal title="Order parts" subtitle={`${store.name} · ${selected.part_name}`} onClose={()=>setSelected(null)}><form className="form-grid" onSubmit={order}><label>Quantity<input name="quantity" type="number" min="1" max={selected.quantity} defaultValue="1" required/></label><label>Order note<textarea name="note" placeholder="Delivery or handling instructions"/></label><p>${Number(selected.price).toFixed(2)} per unit · Recorded billing only</p><button className="primary" disabled={submitting}>{submitting?'Placing order…':'Place order'}</button></form></Modal>}</>
}
